# Generated by Django 5.1 on 2024-08-15 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('IdGenero', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Lanzamiento', models.DateField()),
                ('Clasificacion', models.CharField(max_length=100)),
                ('Duracion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('IdSala', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('Formato', models.BooleanField(default=False)),
                ('Estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Apellido', models.CharField(max_length=100)),
                ('CI', models.IntegerField(unique=True)),
                ('Rol', models.BooleanField(default=False)),
                ('FechaRegistro', models.DateField()),
                ('Estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneroPelicula',
            fields=[
                ('IdGeneroPelicula', models.AutoField(primary_key=True, serialize=False)),
                ('IdGenero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cine.genero')),
                ('IdPelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cine.pelicula')),
            ],
        ),
        migrations.CreateModel(
            name='Funcion',
            fields=[
                ('IdFuncion', models.AutoField(primary_key=True, serialize=False)),
                ('Horario', models.DateTimeField()),
                ('Precio', models.PositiveIntegerField()),
                ('IdPelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cine.pelicula')),
                ('IdSala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cine.sala')),
            ],
        ),
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('IdAsiento', models.AutoField(primary_key=True, serialize=False)),
                ('Numero', models.PositiveIntegerField()),
                ('Fila', models.CharField(max_length=3)),
                ('IdSala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cine.sala')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('IdReserva', models.AutoField(primary_key=True, serialize=False)),
                ('IdAsiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cine.asiento')),
                ('IdUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cine.usuario')),
            ],
        ),
    ]
