# Generated by Django 5.1 on 2024-08-16 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='Genero',
            field=models.ManyToManyField(to='Cine.genero'),
        ),
        migrations.DeleteModel(
            name='GeneroPelicula',
        ),
    ]
