# Generated by Django 5.1 on 2024-08-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cine', '0002_pelicula_genero_delete_generopelicula'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clasificacion',
            fields=[
                ('IdGenero', models.AutoField(primary_key=True, serialize=False)),
                ('Clase', models.CharField(max_length=100)),
            ],
        ),
    ]
