# Generated by Django 5.1 on 2024-08-19 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cine', '0003_clasificacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pelicula',
            old_name='Nombre',
            new_name='Titulo',
        ),
    ]
