# Generated by Django 5.1 on 2024-08-19 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cine', '0004_rename_nombre_pelicula_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='Clasificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cine.clasificacion'),
        ),
    ]
