# Generated by Django 5.1 on 2024-08-22 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cine', '0005_alter_pelicula_clasificacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genero',
            old_name='Nombre',
            new_name='Genero',
        ),
    ]
