# Generated by Django 5.1 on 2024-08-22 15:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cine', '0006_rename_nombre_genero_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='Portada',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pelicula',
            name='Trailer',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
