# Generated by Django 5.1 on 2024-08-22 17:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cine', '0007_pelicula_portada_pelicula_trailer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formato',
            fields=[
                ('IdFormato', models.AutoField(primary_key=True, serialize=False)),
                ('Tipo', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='reserva',
            name='FechaReserva',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='IdFuncion',
            field=models.ForeignKey(default= 0, on_delete=django.db.models.deletion.CASCADE, to='Cine.funcion'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='reserva',
            unique_together={('IdFuncion', 'IdAsiento')},
        ),
        migrations.AlterField(
            model_name='sala',
            name='Formato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cine.formato'),
        ),
    ]
