# Generated by Django 5.1 on 2024-08-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cine', '0008_formato_reserva_fechareserva_reserva_idfuncion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asiento',
            name='Estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='Portada',
            field=models.ImageField(upload_to='cine/media/'),
        ),
    ]
