# Generated by Django 5.1 on 2024-08-22 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cine', '0009_asiento_estado_alter_pelicula_portada'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='Descripcion',
            field=models.TextField(default='Pelicula'),
        ),
    ]
