# Generated by Django 5.1 on 2024-08-30 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Cine", "0010_pelicula_descripcion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="reserva",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="reserva",
            name="Asientos",
            field=models.ManyToManyField(to="Cine.asiento"),
        ),
        migrations.AlterField(
            model_name="reserva",
            name="IdUsuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.RemoveField(
            model_name="reserva",
            name="IdAsiento",
        ),
    ]
