# Generated by Django 5.1 on 2024-08-31 19:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Cine", "0011_alter_reserva_unique_together_reserva_asientos_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reserva",
            name="ReservaQR",
            field=models.ImageField(
                default=django.utils.timezone.now, upload_to="cine/media/reservaQR/"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="pelicula",
            name="Trailer",
            field=models.CharField(max_length=400),
        ),
    ]
